services:
  mysql:
    image: mysql:8.4
    container_name: mysql-pasta
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pasta_db
      MYSQL_USER: pasta_user
      MYSQL_PASSWORD: pasta_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_pasta_data:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_pasta_data: